# Setting server host
server.host: "0.0.0.0"

# Disable the interactive "preboot" enrollment screens
interactiveSetup.enabled: false

# Hosts
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Service token from .env
elasticsearch.serviceAccountToken: "${ELASTIC_SERVICE_TOKEN}"

# Security for enabling plugins & features (generated via docker command)
xpack.security.encryptionKey: "b54b5f06801a16b1849d7989a49acb50"
xpack.encryptedSavedObjects.encryptionKey: "b6780a498c4554487ca6344e44ed236d"
xpack.reporting.encryptionKey: "e274d1862ad70d9c90d7c0ca4052ea26"
