# Setting server host
server.host: "0.0.0.0"
server.publicBaseUrl: "https://localhost:5601"

# --- Kibana HTTPS (browser -> Kibana) ---
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key

# Disable the interactive "preboot" enrollment screens
interactiveSetup.enabled: false

# --- Kibana -> Elasticsearch over HTTPS ---
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.serviceAccountToken: "${ELASTIC_SERVICE_TOKEN}"

# Kibana must trust the CA that signed Elasticsearch's cert & SSL certificate
elasticsearch.ssl.certificateAuthorities:
  ["/usr/share/kibana/config/certs/ca/ca.crt"]
elasticsearch.ssl.verificationMode: certificate

# Security for enabling plugins & features (generated via docker command)
xpack.encryptedSavedObjects.encryptionKey: "e526e6fefcf9d8875f3aba964becdd4a"
xpack.reporting.encryptionKey: "fb2bed2f03f1ff750f3ce3f99e89b384"
xpack.security.encryptionKey: "32b58b4d4f8d4e028db209167675887a"
