server.host: "0.0.0.0"
interactiveSetup.enabled: false

elasticsearch.hosts: ["http://elasticsearch:9200"]

elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_SYSTEM_PASSWORD}"

# Security for enabling plugins & features (generated via docker command)
xpack.encryptedSavedObjects.encryptionKey: "REDACTED"
xpack.reporting.encryptionKey: "REDACTED"
xpack.security.encryptionKey: "REDACTED"
